export const ErrorCode = {
  AUTH_INVALID_STATE: 'AUTH_INVALID_STATE',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
  APPLE_SERVER_TIMEOUT: 'APPLE_SERVER_TIMEOUT',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
