export const ErrorCode = {
  AUTH_INVALID_STATE: 'AUTH_INVALID_STATE',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  DB_TRANSACTION_FAILED: 'DB_TRANSACTION_FAILED',
  APPLE_SERVER_TIMEOUT: 'APPLE_SERVER_TIMEOUT',
  INVITATION_ACCESS_REVOKED: 'INVITATION_ACCESS_REVOKED',
  INVITATION_ID_REQUIRED: 'INVITATION_ID_REQUIRED',
  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  LOCATION_FORBIDDEN: 'LOCATION_FORBIDDEN',
  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_ALREADY_EXISTS: 'PARTICIPANT_ALREADY_EXISTS',
  HOST_CANNOT_LEAVE: 'HOST_CANNOT_LEAVE',
  INVITATION_CLOSED: 'INVITATION_CLOSED',
  RSVP_PERMISSION_DENIED: 'RSVP_PERMISSION_DENIED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
