/**
 * 아이콘 레지스트리 — lucide-react (이전에 쓰던 react 아이콘) 기반.
 * name 기반 API는 그대로 유지(home/bell/user …). 컴포넌트는 IconName만 소비.
 */
import type { LucideIcon } from "lucide-react";
import {
  Home,
  MailOpen,
  Plus,
  Bell,
  User,
  Settings,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Menu,
  X,
  MoreHorizontal,
  Search,
  Filter,
  ArrowUpDown,
  Calendar,
  CalendarClock,
  Clock,
  MapPin,
  Navigation,
  Link,
  Copy,
  Share,
  Edit,
  Trash,
  Eye,
  EyeOff,
  Lock,
  Image as ImageIcon,
  Palette,
  Sparkles,
  Check,
  CircleHelp,
  Users,
  UsersRound,
  UserPlus,
  UserCheck,
  UserX,
  UserRound,
  Hourglass,
  Crown,
  BadgeCheck,
  CircleAlert,
  ClipboardList,
  StickyNote,
  Mail,
  ShieldCheck,
  Download,
  Map as MapIcon,
  LocateFixed,
  ExternalLink,
  Globe,
  TriangleAlert,
  Camera,
  Images,
  Upload,
  Heart,
  Flag,
  RotateCw,
  MessageCircle,
  Send,
  Smile,
  CircleCheck,
  Info,
  Megaphone,
  LogOut,
  UserRoundCog,
  FileText,
  Ticket,
  Sparkle,
  PartyPopper,
} from "lucide-react";

export const ICONS = {
  // Navigation
  home: Home,
  invitation: MailOpen,
  plus: Plus,
  bell: Bell,
  user: User,
  settings: Settings,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  menu: Menu,
  close: X,
  x: X,
  "more-horizontal": MoreHorizontal,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  // Invitation
  calendar: Calendar,
  "calendar-clock": CalendarClock,
  clock: Clock,
  "map-pin": MapPin,
  navigation: Navigation,
  link: Link,
  copy: Copy,
  share: Share,
  edit: Edit,
  trash: Trash,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  image: ImageIcon,
  palette: Palette,
  sparkles: Sparkles,
  // RSVP / Attendance
  check: Check,
  "help-circle": CircleHelp,
  users: Users,
  "users-round": UsersRound,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "user-x": UserX,
  "user-round": UserRound,
  hourglass: Hourglass,
  crown: Crown,
  "badge-check": BadgeCheck,
  "alert-circle": CircleAlert,
  // Participants
  "clipboard-list": ClipboardList,
  memo: StickyNote,
  mail: Mail,
  "shield-check": ShieldCheck,
  download: Download,
  // Map
  map: MapIcon,
  locate: LocateFixed,
  "external-link": ExternalLink,
  globe: Globe,
  "alert-triangle": TriangleAlert,
  // Album
  camera: Camera,
  images: Images,
  upload: Upload,
  heart: Heart,
  flag: Flag,
  "rotate-cw": RotateCw,
  // Comments
  "message-circle": MessageCircle,
  send: Send,
  smile: Smile,
  // Notifications
  "check-circle": CircleCheck,
  info: Info,
  megaphone: Megaphone,
  // Auth
  "log-out": LogOut,
  "user-round-cog": UserRoundCog,
  "file-text": FileText,
  // 장식/브랜드 (lucide 대응)
  "retro-camera": Camera,
  ticket: Ticket,
  sparkle: Sparkle,
  "party-popper": PartyPopper,
  "instagram-logo": Camera, // lucide에 Instagram 브랜드 아이콘 없음 → Camera 대체
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
