/**
 * 토큰 TS → css/tokens.css 생성기 (의존성 0, Node 네이티브 TS 실행).
 * 실행: `pnpm -F @wara/tokens generate`
 *
 * 구조:
 *  - :root            테마 전환 토큰(색·글래스·그림자·focus·blur)의 light 기본값
 *  - [data-theme=dark] 동일 토큰의 dark 오버라이드
 *  - @theme inline    Tailwind 유틸리티 ↔ 런타임 var 매핑 (재컴파일 없이 전환)
 *  - @theme           고정 토큰(primitive 색·radius·폰트·이징·의미 스페이싱) 리터럴
 *  - @custom-variant  dark: [data-theme=dark] 스코프
 *  - .type-*          한글 타이포 유틸 클래스
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { colorPrimitives, semanticColors } from "../src/colors.ts";
import { gradient } from "../src/gradient.ts";
import { glass, blur } from "../src/glass.ts";
import { typeScale, fontFamily } from "../src/typography.ts";
import { spacingSemanticPx } from "../src/spacing.ts";
import { radiusPx } from "../src/radius.ts";
import { shadow } from "../src/shadow.ts";
import { duration, easing } from "../src/motion.ts";
import { zIndex } from "../src/zIndex.ts";

const rem = (px: number) => `${px / 16}rem`;

// ── 테마 전환 토큰: light 기본 + dark 오버라이드 ─────────────────────────────
const themeVars = (mode: "light" | "dark") => {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(semanticColors[mode]))
    lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(glass[mode])) lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(gradient[mode]))
    lines.push(`  --${k}: ${v};`);
  for (const [k, v] of Object.entries(shadow[mode]))
    lines.push(`  --ev-${k}: ${v};`);
  lines.push(`  --blur-glass: ${mode === "dark" ? "18px" : "16px"};`);
  lines.push(`  --blur-glass-strong: ${blur["glass-strong"]};`);
  const ring =
    mode === "dark"
      ? "0 0 0 3px rgba(244,241,250,0.34)"
      : "0 0 0 3px rgba(20,18,26,0.28)";
  lines.push(`  --focus-ring: ${ring};`);
  return lines.join("\n");
};

// ── @theme inline: 전환 토큰을 Tailwind 유틸로 노출 ──────────────────────────
const themeInline = () => {
  const lines: string[] = [];
  for (const k of Object.keys(semanticColors.light))
    lines.push(`  --color-${k}: var(--${k});`);
  for (const k of Object.keys(glass.light))
    lines.push(`  --color-${k}: var(--${k});`);
  for (const k of Object.keys(shadow.light))
    lines.push(`  --shadow-${k}: var(--ev-${k});`);
  return lines.join("\n");
};

// ── @theme: 고정 토큰 리터럴 ─────────────────────────────────────────────────
const themeStatic = () => {
  const lines: string[] = [];
  // primitive 색 스케일 → bg-purple-500 등
  for (const [name, scale] of Object.entries(colorPrimitives))
    for (const [step, v] of Object.entries(scale))
      lines.push(`  --color-${name}-${step}: ${v};`);
  // radius
  for (const [k, v] of Object.entries(radiusPx))
    lines.push(`  --radius-${k}: ${v >= 9999 ? "9999px" : `${v}px`};`);
  // 폰트
  lines.push(`  --font-sans: ${fontFamily.sans};`);
  lines.push(`  --font-display: ${fontFamily.display};`);
  // 이징
  for (const [k, v] of Object.entries(easing)) lines.push(`  --ease-${k}: ${v};`);
  // 의미 스페이싱
  for (const [k, v] of Object.entries(spacingSemanticPx))
    lines.push(`  --spacing-${k}: ${rem(v)};`);
  return lines.join("\n");
};

// ── 비유틸 :root 토큰(z-index, duration, 타이포 변수) ────────────────────────
const rootExtras = () => {
  const lines: string[] = [];
  for (const [k, v] of Object.entries(zIndex)) lines.push(`  --z-${k}: ${v};`);
  for (const [k, v] of Object.entries(duration))
    lines.push(`  --duration-${k}: ${v};`);
  for (const [variant, s] of Object.entries(typeScale)) {
    lines.push(`  --type-${variant}-size: ${rem(s.size)};`);
    lines.push(`  --type-${variant}-weight: ${s.weight};`);
    lines.push(`  --type-${variant}-leading: ${s.lineHeight};`);
    lines.push(`  --type-${variant}-tracking: ${s.letterSpacing}em;`);
  }
  return lines.join("\n");
};

// ── 타이포 유틸 클래스 ───────────────────────────────────────────────────────
const typeClasses = () =>
  Object.keys(typeScale)
    .map(
      (v) =>
        `.type-${v} {\n` +
        `  font-size: var(--type-${v}-size);\n` +
        `  font-weight: var(--type-${v}-weight);\n` +
        `  line-height: var(--type-${v}-leading);\n` +
        `  letter-spacing: var(--type-${v}-tracking);\n` +
        `}`,
    )
    .join("\n");

export const buildCss = (): string => `/**
 * GENERATED by @wara/tokens — DO NOT EDIT BY HAND.
 * Edit packages/tokens/src/*.ts then run \`pnpm -F @wara/tokens generate\`.
 */

:root {
${themeVars("light")}
${rootExtras()}
}

[data-theme="dark"] {
${themeVars("dark")}
}

@custom-variant dark (&:where([data-theme="dark"], [data-theme="dark"] *));

@theme inline {
${themeInline()}
}

@theme {
${themeStatic()}
}

@layer base {
  :focus-visible {
    outline: none;
    box-shadow: var(--focus-ring);
  }
}

@layer utilities {
${typeClasses()}
}
`;

const outPath = () =>
  join(dirname(fileURLToPath(import.meta.url)), "..", "css", "tokens.css");

// 직접 실행 시에만 파일 기록 (테스트에서 import 시엔 부작용 없음)
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const css = buildCss();
  mkdirSync(dirname(outPath()), { recursive: true });
  writeFileSync(outPath(), css, "utf8");
  console.log(`✓ wrote ${outPath()} (${css.length} bytes)`);
}
