import type { ComponentType } from "react";
import type { LucideProps } from "lucide-react";
import {
  Home,
  MailOpen,
  Plus,
  Bell,
  User,
  Settings,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  Menu,
  X,
  MoreHorizontal,
  Search,
  Filter,
  ArrowUpDown,
  Calendar,
  Clock,
  MapPin,
  Navigation,
  Link,
  Copy,
  Share,
  QrCode,
  Edit,
  Trash,
  Save,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Image as ImageIcon,
  Palette,
  Sparkles,
  Check,
  CircleHelp,
  Users,
  UserPlus,
  UserCheck,
  UserX,
  Hourglass,
  Crown,
  BadgeCheck,
  CircleAlert,
  CirclePlus,
  CircleMinus,
  Minus,
  UserRound,
  UsersRound,
  MessageSquare,
  ClipboardList,
  StickyNote,
  Mail,
  Phone,
  Shield,
  Download,
  Map,
  LocateFixed,
  Route,
  ExternalLink,
  Building,
  Globe,
  Wifi,
  TriangleAlert,
  Camera,
  Images,
  Upload,
  Heart,
  Flag,
  RotateCw,
  ZoomIn,
  MessageCircle,
  Send,
  Reply,
  Smile,
  BellDot,
  CircleCheck,
  CircleX,
  Info,
  CalendarClock,
  Megaphone,
  LogOut,
  UserRoundCog,
  ShieldCheck,
  FileText,
  LockKeyhole,
} from "lucide-react";

import {
  PixelAirplane,
  PixelHeart,
  Sparkle,
  Ribbon,
  StickerFlower,
  StickerSmile,
  RetroCamera,
  Ticket,
  PartyPopper,
  MiniCloud,
  MiniBow,
  PixelCheck,
  KakaoLogo,
  NaverLogo,
  AppleLogo,
  AppleLogoWhite,
  GoogleLogo,
  CrownYellow,
} from "./custom";

import type { IconName } from "./types";

export const ICON_REGISTRY: Record<IconName, ComponentType<LucideProps>> = {
  // Navigation
  home: Home,
  invitation: MailOpen,
  plus: Plus,
  bell: Bell,
  user: User,
  settings: Settings,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-down": ChevronDown,
  menu: Menu,
  close: X,
  "more-horizontal": MoreHorizontal,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,

  // Invitation
  calendar: Calendar,
  clock: Clock,
  "map-pin": MapPin,
  navigation: Navigation,
  link: Link,
  copy: Copy,
  share: Share,
  qrcode: QrCode,
  edit: Edit,
  trash: Trash,
  save: Save,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  image: ImageIcon,
  palette: Palette,
  sparkles: Sparkles,

  // RSVP / Attendance
  check: Check,
  "help-circle": CircleHelp,
  x: X,
  users: Users,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "user-x": UserX,
  hourglass: Hourglass,
  crown: Crown,
  "crown-yellow": CrownYellow,
  "badge-check": BadgeCheck,
  "alert-circle": CircleAlert,
  "plus-circle": CirclePlus,
  "minus-circle": CircleMinus,
  minus: Minus,

  // Participants
  "user-round": UserRound,
  "users-round": UsersRound,
  "message-square": MessageSquare,
  "clipboard-list": ClipboardList,
  memo: StickyNote,
  mail: Mail,
  phone: Phone,
  shield: Shield,
  download: Download,

  // Map
  map: Map,
  locate: LocateFixed,
  route: Route,
  "external-link": ExternalLink,
  building: Building,
  globe: Globe,
  wifi: Wifi,
  "alert-triangle": TriangleAlert,

  // Album
  camera: Camera,
  images: Images,
  upload: Upload,
  heart: Heart,
  flag: Flag,
  "rotate-cw": RotateCw,
  "zoom-in": ZoomIn,

  // Comments
  "message-circle": MessageCircle,
  send: Send,
  reply: Reply,
  smile: Smile,

  // Notifications
  "bell-dot": BellDot,
  "check-circle": CircleCheck,
  "x-circle": CircleX,
  info: Info,
  "calendar-clock": CalendarClock,
  megaphone: Megaphone,

  // Auth
  "log-out": LogOut,
  "user-round-cog": UserRoundCog,
  "shield-check": ShieldCheck,
  "file-text": FileText,
  "lock-keyhole": LockKeyhole,

  // Wara decorative
  "pixel-airplane": PixelAirplane,
  "pixel-heart": PixelHeart,
  sparkle: Sparkle,
  ribbon: Ribbon,
  "sticker-flower": StickerFlower,
  "sticker-smile": StickerSmile,
  "retro-camera": RetroCamera,
  ticket: Ticket,
  "party-popper": PartyPopper,
  "mini-cloud": MiniCloud,
  "mini-bow": MiniBow,
  "pixel-check": PixelCheck,

  // Social
  "kakao-logo": KakaoLogo,
  "naver-logo": NaverLogo,
  "apple-logo": AppleLogo,
  "apple-logo-white": AppleLogoWhite,
  "google-logo": GoogleLogo,
};

const BRAND_ICONS: ReadonlySet<IconName> = new Set([
  "kakao-logo",
  "naver-logo",
  "apple-logo",
  "apple-logo-white",
  "google-logo",
  "crown-yellow",
]);

export const isBrandIcon = (name: IconName): boolean => BRAND_ICONS.has(name);
