export const ROUTES = {
  HOME: "/",
  CALENDAR: "/calendar",
  FRIENDS: "/friends",
  SIGNUP: "/signup",
  LOGIN: "/login",
  INVITATIONS: {
    LIST: "/invitations",
    CREATE: "/invitations/create",
    DETAIL: (id: string) => `/invitations/${id}`,
    EDIT: (id: string) => `/invitations/${id}/edit`,
    PARTICIPANTS: (id: string) => `/invitations/${id}/participants`,
    MISSIONS: (id: string) => `/invitations/${id}/missions`,
    MISSION_DETAIL: (id: string, missionId: string) => `/invitations/${id}/missions/${missionId}`,
    PHOTOS: (id: string) => `/invitations/${id}/photos`,
    PHOTO_DETAIL: (id: string, photoId: string) => `/invitations/${id}/photos/${photoId}`,
    PHOTOS_BEST9: (id: string) => `/invitations/${id}/photos/best9`,
    FEEDBACKS: (id: string) => `/invitations/${id}/feedbacks`,
    LOCATION: (id: string) => `/invitations/${id}/location`,
    SETTINGS: (id: string) => `/invitations/${id}/settings`,
    VOTE: (id: string) => `/invitations/${id}/vote`,
  },
  PUBLIC: {
    INVITATION: (id: string) => `/invitations/${id}`,
  },
  NOTIFICATIONS: {
    LIST: "/notifications",
    SETTINGS: "/notifications/settings",
  },
  PROFILE: {
    ME: "/profile",
    EDIT: "/profile/edit",
    SETTINGS: "/profile/settings",
    ACCOUNT: "/profile/account",
  },
  ADMIN: {
    INQUIRIES: '/admin/inquiries',
    INQUIRY_DETAIL: (id: string) => `/admin/inquiries/${id}`,
    FAQ: '/admin/faq',
  },
  INQUIRIES: {
    HOME: "/inquiries",
    WRITE: "/inquiries/write",
    LIST: "/inquiries/list",
    ME: "/inquiries/me",
    DETAIL: (id: string) => `/inquiries/${id}`,
  },
  TERMS: {
    AGREE: "/terms/agree",
  },
} as const;
