import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 420, height: 360 }, deviceScaleFactor: 2 });
await p.goto('http://localhost:3300/verify-tmp', { waitUntil: 'domcontentloaded' });
await p.waitForTimeout(700);
await p.screenshot({ path: '/tmp/r4b_empty.png', fullPage: true });
const ta = p.locator('textarea').first();
await ta.click(); await ta.type('가는중! @park');
await p.waitForTimeout(200);
await p.screenshot({ path: '/tmp/r4b_typed.png', fullPage: true });
await b.close(); console.log('ok');
